sudo: required
dist: trusty
language: python

branches:
  except:
    - docker-integration
    - docker-test

env:
  global:
    - ANDROID_SDK=4333796
    - BAZEL=0.22.0
    - JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 2.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      python: 3.3
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      python: 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      language: cpp
      env:
        - PY=/usr/bin/python2.7
        - MATRIX_EVAL=""
  allow_failures:
    - os: osx
      language: cpp
      env:
        - PY=/usr/bin/python2.7
        - MATRIX_EVAL=""

before_install:
  - eval "${MATRIX_EVAL}"
  - . travis/before_install.sh

install:
  - yes | "$ANDROID_HOME/tools/bin/sdkmanager" 'build-tools;28.0.2' 'platforms;android-28' > /dev/null
  - pip install -r travis/requirements.txt

script:
  - travis/script.sh
