sudo: required
dist: trusty

env:
  - BAZEL=0.3.1

before_install:
  - sudo apt-get update -qq
  # Bazel dependencies:
  - sudo apt-get install -qq pkg-config zip g++ zlib1g-dev unzip
  # Project dependencies:
  - sudo apt-get install -qq python-pyicu
  # Install Bazel:
  - wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL}/bazel-${BAZEL}-installer-linux-x86_64.sh
  - sha256sum -c third_party/bazel-${BAZEL}-installer-linux-x86_64.sh.sha256
  - bash bazel-${BAZEL}-installer-linux-x86_64.sh --user
  # Install Android SDK:
  - sudo mkdir -p /usr/local/android-sdk
  - sudo chmod 1777 /usr/local/android-sdk
  - wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar xzf android-sdk_r24.4.1-linux.tgz -C /usr/local/android-sdk --strip-components=1
  - echo y | /usr/local/android-sdk/tools/android update sdk --no-ui --all --filter build-tools-24.0.3
  - echo y | /usr/local/android-sdk/tools/android update sdk --no-ui --all --filter android-24

script:
  - bazel test //af/... //bn/... //festus/... //hi_ur/... //my/... //Mymr/... //si/... //xh/... //zu/...
